/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BulkheadFactoryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_CLUSTER_SIZE" | "allBulkheads" | "cluster" | "createBulkhead" | "createCluster" | "nextClusterId" | "overseer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BulkheadCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_CLUSTER_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'allBulkheads', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cluster', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createBulkhead', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createCluster', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextClusterId', values?: undefined): string;
encodeFunctionData(functionFragment: 'overseer', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_CLUSTER_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allBulkheads', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cluster', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBulkhead', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCluster', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextClusterId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'overseer', data: BytesLike): Result;
  }

  
    export namespace BulkheadCreatedEvent {
      export type InputTuple = [bulkhead: AddressLike, clusterId: BigNumberish, indexInCluster: BigNumberish];
      export type OutputTuple = [bulkhead: string, clusterId: bigint, indexInCluster: bigint];
      export interface OutputObject {bulkhead: string, clusterId: bigint, indexInCluster: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BulkheadFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): BulkheadFactory;
    waitForDeployment(): Promise<this>;

    interface: BulkheadFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_CLUSTER_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allBulkheads: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    cluster: TypedContractMethod<
      [clusterId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    createBulkhead: TypedContractMethod<
      [clusterId: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    createCluster: TypedContractMethod<
      [clusterId: BigNumberish, count: BigNumberish, ],
      [string[]],
      'nonpayable'
    >
    

    
    nextClusterId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    overseer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_CLUSTER_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allBulkheads'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cluster'): TypedContractMethod<
      [clusterId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'createBulkhead'): TypedContractMethod<
      [clusterId: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createCluster'): TypedContractMethod<
      [clusterId: BigNumberish, count: BigNumberish, ],
      [string[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextClusterId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'overseer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'BulkheadCreated'): TypedContractEvent<BulkheadCreatedEvent.InputTuple, BulkheadCreatedEvent.OutputTuple, BulkheadCreatedEvent.OutputObject>;

    filters: {
      
      'BulkheadCreated(address,uint256,uint256)': TypedContractEvent<BulkheadCreatedEvent.InputTuple, BulkheadCreatedEvent.OutputTuple, BulkheadCreatedEvent.OutputObject>;
      BulkheadCreated: TypedContractEvent<BulkheadCreatedEvent.InputTuple, BulkheadCreatedEvent.OutputTuple, BulkheadCreatedEvent.OutputObject>;
    
    };
  }