/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BulkheadFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BulkheadFactory__factory>
getContractFactory(name: 'Bulkhead', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Bulkhead__factory>
getContractFactory(name: 'MockPrecompile', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPrecompile__factory>

  getContractAt(name: 'BulkheadFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BulkheadFactory>
getContractAt(name: 'Bulkhead', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Bulkhead>
getContractAt(name: 'MockPrecompile', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPrecompile>

  deployContract(name: 'BulkheadFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BulkheadFactory>
deployContract(name: 'Bulkhead', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Bulkhead>
deployContract(name: 'MockPrecompile', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompile>

  deployContract(name: 'BulkheadFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BulkheadFactory>
deployContract(name: 'Bulkhead', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Bulkhead>
deployContract(name: 'MockPrecompile', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompile>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  