/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AttestationGateway', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AttestationGateway__factory>
getContractFactory(name: 'INativeQueryVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INativeQueryVerifier__factory>
getContractFactory(name: 'BulkheadFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BulkheadFactory__factory>
getContractFactory(name: 'Bulkhead', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Bulkhead__factory>
getContractFactory(name: 'IAttestationGateway', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAttestationGateway__factory>
getContractFactory(name: 'Overseer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Overseer__factory>
getContractFactory(name: 'MockDistressSignal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockDistressSignal__factory>
getContractFactory(name: 'MockReceiptEncoder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockReceiptEncoder__factory>
getContractFactory(name: 'MockPrecompile', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPrecompile__factory>

  getContractAt(name: 'AttestationGateway', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AttestationGateway>
getContractAt(name: 'INativeQueryVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INativeQueryVerifier>
getContractAt(name: 'BulkheadFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BulkheadFactory>
getContractAt(name: 'Bulkhead', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Bulkhead>
getContractAt(name: 'IAttestationGateway', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAttestationGateway>
getContractAt(name: 'Overseer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Overseer>
getContractAt(name: 'MockDistressSignal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockDistressSignal>
getContractAt(name: 'MockReceiptEncoder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockReceiptEncoder>
getContractAt(name: 'MockPrecompile', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPrecompile>

  deployContract(name: 'AttestationGateway', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttestationGateway>
deployContract(name: 'INativeQueryVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INativeQueryVerifier>
deployContract(name: 'BulkheadFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BulkheadFactory>
deployContract(name: 'Bulkhead', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Bulkhead>
deployContract(name: 'IAttestationGateway', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAttestationGateway>
deployContract(name: 'Overseer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Overseer>
deployContract(name: 'MockDistressSignal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockDistressSignal>
deployContract(name: 'MockReceiptEncoder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockReceiptEncoder>
deployContract(name: 'MockPrecompile', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompile>

  deployContract(name: 'AttestationGateway', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttestationGateway>
deployContract(name: 'INativeQueryVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INativeQueryVerifier>
deployContract(name: 'BulkheadFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BulkheadFactory>
deployContract(name: 'Bulkhead', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Bulkhead>
deployContract(name: 'IAttestationGateway', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAttestationGateway>
deployContract(name: 'Overseer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Overseer>
deployContract(name: 'MockDistressSignal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockDistressSignal>
deployContract(name: 'MockReceiptEncoder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockReceiptEncoder>
deployContract(name: 'MockPrecompile', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompile>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  