/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IAttestationGateway, IAttestationGatewayInterface } from "../../Overseer.sol/IAttestationGateway.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "queryId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint64",
        "name": "chainKey",
        "type": "uint64"
      },
      {
        "indexed": true,
        "internalType": "uint64",
        "name": "height",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "encodedTransaction",
        "type": "bytes"
      }
    ],
    "name": "VerifiedData",
    "type": "event"
  }
] as const;

  export class IAttestationGateway__factory {
    static readonly abi = _abi;
    static createInterface(): IAttestationGatewayInterface {
      return new Interface(_abi) as IAttestationGatewayInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IAttestationGateway {
      return new Contract(address, _abi, runner) as unknown as IAttestationGateway;
    }
  }
  