/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockPrecompileInterface extends Interface {
    getFunction(nameOrSignature: "configure" | "receiptStatus" | "shouldVerify" | "txData" | "verifyAndEmit"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "VerifyCalled"): EventFragment;

    encodeFunctionData(functionFragment: 'configure', values: [boolean, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'receiptStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'shouldVerify', values?: undefined): string;
encodeFunctionData(functionFragment: 'txData', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyAndEmit', values: [BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'configure', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiptStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'txData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyAndEmit', data: BytesLike): Result;
  }

  
    export namespace VerifyCalledEvent {
      export type InputTuple = [chainKey: BigNumberish, height: BigNumberish, receiptStatus: BigNumberish];
      export type OutputTuple = [chainKey: bigint, height: bigint, receiptStatus: bigint];
      export interface OutputObject {chainKey: bigint, height: bigint, receiptStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockPrecompile extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockPrecompile;
    waitForDeployment(): Promise<this>;

    interface: MockPrecompileInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    configure: TypedContractMethod<
      [verify_: boolean, status_: BigNumberish, txData_: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    receiptStatus: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    shouldVerify: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    txData: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyAndEmit: TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, arg2: BytesLike, arg3: BytesLike, arg4: BytesLike, ],
      [[boolean, bigint, string]],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'configure'): TypedContractMethod<
      [verify_: boolean, status_: BigNumberish, txData_: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'receiptStatus'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'shouldVerify'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'txData'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyAndEmit'): TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, arg2: BytesLike, arg3: BytesLike, arg4: BytesLike, ],
      [[boolean, bigint, string]],
      'nonpayable'
    >;

    getEvent(key: 'VerifyCalled'): TypedContractEvent<VerifyCalledEvent.InputTuple, VerifyCalledEvent.OutputTuple, VerifyCalledEvent.OutputObject>;

    filters: {
      
      'VerifyCalled(uint64,uint64,uint8)': TypedContractEvent<VerifyCalledEvent.InputTuple, VerifyCalledEvent.OutputTuple, VerifyCalledEvent.OutputObject>;
      VerifyCalled: TypedContractEvent<VerifyCalledEvent.InputTuple, VerifyCalledEvent.OutputTuple, VerifyCalledEvent.OutputObject>;
    
    };
  }