/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockDistressSignalInterface extends Interface {
    getFunction(nameOrSignature: "emitDistress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DistressSignal"): EventFragment;

    encodeFunctionData(functionFragment: 'emitDistress', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'emitDistress', data: BytesLike): Result;
  }

  
    export namespace DistressSignalEvent {
      export type InputTuple = [clusterId: BigNumberish, distressBps: BigNumberish];
      export type OutputTuple = [clusterId: bigint, distressBps: bigint];
      export interface OutputObject {clusterId: bigint, distressBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockDistressSignal extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockDistressSignal;
    waitForDeployment(): Promise<this>;

    interface: MockDistressSignalInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    emitDistress: TypedContractMethod<
      [clusterId: BigNumberish, distressBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'emitDistress'): TypedContractMethod<
      [clusterId: BigNumberish, distressBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DistressSignal'): TypedContractEvent<DistressSignalEvent.InputTuple, DistressSignalEvent.OutputTuple, DistressSignalEvent.OutputObject>;

    filters: {
      
      'DistressSignal(uint256,uint256)': TypedContractEvent<DistressSignalEvent.InputTuple, DistressSignalEvent.OutputTuple, DistressSignalEvent.OutputObject>;
      DistressSignal: TypedContractEvent<DistressSignalEvent.InputTuple, DistressSignalEvent.OutputTuple, DistressSignalEvent.OutputObject>;
    
    };
  }