/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace INativeQueryVerifier {
      
    export type MerkleProofEntryStruct = {hash: BytesLike, isLeft: boolean}

    export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {hash: string, isLeft: boolean }
  

    export type MerkleProofStruct = {root: BytesLike, siblings: INativeQueryVerifier.MerkleProofEntryStruct[]}

    export type MerkleProofStructOutput = [root: string, siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[]] & {root: string, siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[] }
  

    export type ContinuityProofStruct = {lowerEndpointDigest: BytesLike, roots: BytesLike[]}

    export type ContinuityProofStructOutput = [lowerEndpointDigest: string, roots: string[]] & {lowerEndpointDigest: string, roots: string[] }
  
    }

export declare namespace AttestationGateway {
      
    export type QueryStruct = {chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: INativeQueryVerifier.MerkleProofStruct, continuityProof: INativeQueryVerifier.ContinuityProofStruct}

    export type QueryStructOutput = [chainKey: bigint, height: bigint, encodedTransaction: string, merkleProof: INativeQueryVerifier.MerkleProofStructOutput, continuityProof: INativeQueryVerifier.ContinuityProofStructOutput] & {chainKey: bigint, height: bigint, encodedTransaction: string, merkleProof: INativeQueryVerifier.MerkleProofStructOutput, continuityProof: INativeQueryVerifier.ContinuityProofStructOutput }
  
    }

  export interface AttestationGatewayInterface extends Interface {
    getFunction(nameOrSignature: "PRECOMPILE_ADDRESS" | "verify" | "verifyBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "VerifiedData"): EventFragment;

    encodeFunctionData(functionFragment: 'PRECOMPILE_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'verify', values: [AttestationGateway.QueryStruct]): string;
encodeFunctionData(functionFragment: 'verifyBatch', values: [AttestationGateway.QueryStruct[]]): string;

    decodeFunctionResult(functionFragment: 'PRECOMPILE_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyBatch', data: BytesLike): Result;
  }

  
    export namespace VerifiedDataEvent {
      export type InputTuple = [queryId: BytesLike, chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike];
      export type OutputTuple = [queryId: string, chainKey: bigint, height: bigint, encodedTransaction: string];
      export interface OutputObject {queryId: string, chainKey: bigint, height: bigint, encodedTransaction: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AttestationGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): AttestationGateway;
    waitForDeployment(): Promise<this>;

    interface: AttestationGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PRECOMPILE_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [query: AttestationGateway.QueryStruct, ],
      [string],
      'nonpayable'
    >
    

    
    verifyBatch: TypedContractMethod<
      [queries: AttestationGateway.QueryStruct[], ],
      [string[]],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PRECOMPILE_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [query: AttestationGateway.QueryStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyBatch'): TypedContractMethod<
      [queries: AttestationGateway.QueryStruct[], ],
      [string[]],
      'nonpayable'
    >;

    getEvent(key: 'VerifiedData'): TypedContractEvent<VerifiedDataEvent.InputTuple, VerifiedDataEvent.OutputTuple, VerifiedDataEvent.OutputObject>;

    filters: {
      
      'VerifiedData(bytes32,uint64,uint64,bytes)': TypedContractEvent<VerifiedDataEvent.InputTuple, VerifiedDataEvent.OutputTuple, VerifiedDataEvent.OutputObject>;
      VerifiedData: TypedContractEvent<VerifiedDataEvent.InputTuple, VerifiedDataEvent.OutputTuple, VerifiedDataEvent.OutputObject>;
    
    };
  }