/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AttestationGateway } from './AttestationGateway.js';
export type { INativeQueryVerifier } from './INativeQueryVerifier.js';