/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../common.js"
  

  export interface IAttestationGatewayInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "VerifiedData"): EventFragment;

    

    
  }

  
    export namespace VerifiedDataEvent {
      export type InputTuple = [queryId: BytesLike, chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike];
      export type OutputTuple = [queryId: string, chainKey: bigint, height: bigint, encodedTransaction: string];
      export interface OutputObject {queryId: string, chainKey: bigint, height: bigint, encodedTransaction: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IAttestationGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAttestationGateway;
    waitForDeployment(): Promise<this>;

    interface: IAttestationGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'VerifiedData'): TypedContractEvent<VerifiedDataEvent.InputTuple, VerifiedDataEvent.OutputTuple, VerifiedDataEvent.OutputObject>;

    filters: {
      
      'VerifiedData(bytes32,uint64,uint64,bytes)': TypedContractEvent<VerifiedDataEvent.InputTuple, VerifiedDataEvent.OutputTuple, VerifiedDataEvent.OutputObject>;
      VerifiedData: TypedContractEvent<VerifiedDataEvent.InputTuple, VerifiedDataEvent.OutputTuple, VerifiedDataEvent.OutputObject>;
    
    };
  }