/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAttestationGateway } from './IAttestationGateway.js';
export type { Overseer } from './Overseer.js';