/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface OverseerInterface extends Interface {
    getFunction(nameOrSignature: "DISTRESS_THRESHOLD_BPS" | "clusterBulkheads" | "gateway" | "processVerifiedData" | "processedQuery" | "registerCluster" | "registryAdmin"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BulkheadHalted" | "ClusterRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'DISTRESS_THRESHOLD_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'clusterBulkheads', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'gateway', values?: undefined): string;
encodeFunctionData(functionFragment: 'processVerifiedData', values: [BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'processedQuery', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'registerCluster', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'registryAdmin', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DISTRESS_THRESHOLD_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clusterBulkheads', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gateway', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processVerifiedData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedQuery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCluster', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registryAdmin', data: BytesLike): Result;
  }

  
    export namespace BulkheadHaltedEvent {
      export type InputTuple = [bulkhead: AddressLike, clusterId: BigNumberish, queryId: BytesLike, distressBps: BigNumberish, thresholdBps: BigNumberish];
      export type OutputTuple = [bulkhead: string, clusterId: bigint, queryId: string, distressBps: bigint, thresholdBps: bigint];
      export interface OutputObject {bulkhead: string, clusterId: bigint, queryId: string, distressBps: bigint, thresholdBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClusterRegisteredEvent {
      export type InputTuple = [clusterId: BigNumberish, bulkheads: AddressLike[]];
      export type OutputTuple = [clusterId: bigint, bulkheads: string[]];
      export interface OutputObject {clusterId: bigint, bulkheads: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Overseer extends BaseContract {
    
    connect(runner?: ContractRunner | null): Overseer;
    waitForDeployment(): Promise<this>;

    interface: OverseerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DISTRESS_THRESHOLD_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    clusterBulkheads: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    gateway: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    processVerifiedData: TypedContractMethod<
      [queryId: BytesLike, clusterId: BigNumberish, distressBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    processedQuery: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    registerCluster: TypedContractMethod<
      [clusterId: BigNumberish, bulkheads: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    registryAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DISTRESS_THRESHOLD_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'clusterBulkheads'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'gateway'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'processVerifiedData'): TypedContractMethod<
      [queryId: BytesLike, clusterId: BigNumberish, distressBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'processedQuery'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerCluster'): TypedContractMethod<
      [clusterId: BigNumberish, bulkheads: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registryAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'BulkheadHalted'): TypedContractEvent<BulkheadHaltedEvent.InputTuple, BulkheadHaltedEvent.OutputTuple, BulkheadHaltedEvent.OutputObject>;
getEvent(key: 'ClusterRegistered'): TypedContractEvent<ClusterRegisteredEvent.InputTuple, ClusterRegisteredEvent.OutputTuple, ClusterRegisteredEvent.OutputObject>;

    filters: {
      
      'BulkheadHalted(address,uint256,bytes32,uint256,uint256)': TypedContractEvent<BulkheadHaltedEvent.InputTuple, BulkheadHaltedEvent.OutputTuple, BulkheadHaltedEvent.OutputObject>;
      BulkheadHalted: TypedContractEvent<BulkheadHaltedEvent.InputTuple, BulkheadHaltedEvent.OutputTuple, BulkheadHaltedEvent.OutputObject>;
    

      'ClusterRegistered(uint256,address[])': TypedContractEvent<ClusterRegisteredEvent.InputTuple, ClusterRegisteredEvent.OutputTuple, ClusterRegisteredEvent.OutputObject>;
      ClusterRegistered: TypedContractEvent<ClusterRegisteredEvent.InputTuple, ClusterRegisteredEvent.OutputTuple, ClusterRegisteredEvent.OutputObject>;
    
    };
  }