/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockDistressSignal, MockDistressSignalInterface } from "../../mocks/MockDistressSignal.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "clusterId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "distressBps",
        "type": "uint256"
      }
    ],
    "name": "DistressSignal",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "clusterId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "distressBps",
        "type": "uint256"
      }
    ],
    "name": "emitDistress",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060cd8061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c8063803ff6e514602a575b5f80fd5b603960353660046078565b603b565b005b817f10cf151375217cd01d0bcddfa3eb9af8f80d824eb309d9c9cb47618085b9ee2682604051606c91815260200190565b60405180910390a25050565b5f80604083850312156088575f80fd5b5050803592602090910135915056fea26469706673582212200224ff44406f95d739c347d1e0afaa6eabb6ff792464e6bc7343da9a66f2718064736f6c63430008180033";

  
      type MockDistressSignalConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockDistressSignalConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockDistressSignal__factory extends ContractFactory {
    
      constructor(...args: MockDistressSignalConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockDistressSignal & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockDistressSignal__factory {
      return super.connect(runner) as MockDistressSignal__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockDistressSignalInterface {
      return new Interface(_abi) as MockDistressSignalInterface;
    }
    
    override attach(address: string | Addressable): MockDistressSignal {
      return super.attach(address) as MockDistressSignal;
    }
  static connect(address: string, runner?: ContractRunner | null): MockDistressSignal {
      return new Contract(address, _abi, runner) as unknown as MockDistressSignal;
    }
  }

  
  