/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockReceiptEncoder, MockReceiptEncoderInterface } from "../../mocks/MockReceiptEncoder.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "status",
        "type": "uint8"
      }
    ],
    "name": "encode",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506103a38061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c8063377c7a8c1461002d575b5f80fd5b61004061003b36600461018a565b610056565b60405161004d91906101f4565b60405180910390f35b60408051600280825260608281019093525f9190816020015b606081526020019060019003908161006f5790505090506040518060400160405280600181526020015f815250815f815181106100ae576100ae610206565b6020908102919091010152825f8060405190808252806020026020018201604052801561011957816020015b61010660405180606001604052805f6001600160a01b0316815260200160608152602001606081525090565b8152602001906001900390816100da5790505b50604080515f815260208101825261013594939291810161021a565b6040516020818303038152906040528160018151811061015757610157610206565b602002602001018190525080604051602001610173919061030b565b604051602081830303815290604052915050919050565b5f6020828403121561019a575f80fd5b813560ff811681146101aa575f80fd5b9392505050565b5f81518084525f5b818110156101d5576020818501810151868301820152016101b9565b505f602082860101526020601f19601f83011685010191505092915050565b602081525f6101aa60208301846101b1565b634e487b7160e01b5f52603260045260245ffd5b5f608080830160ff88168452602067ffffffffffffffff88168186015260406080604087015282885180855260a08801915060a08160051b8901019450838a015f5b828110156102e757898703609f19018452815180516001600160a01b03168852868101516060888a018190528151908a018190528a8a01918901905f905b808210156102ba5782518452928a0192918a01916001919091019061029a565b5050509086015188820389880152906102d381836101b1565b98505050928501929085019060010161025c565b50505050505083810360608501526102ff81866101b1565b98975050505050505050565b5f60208083016020845280855180835260408601915060408160051b8701019250602087015f5b8281101561036057603f1988860301845261034e8583516101b1565b94509285019290850190600101610332565b509297965050505050505056fea2646970667358221220a023a116a209ee67dc518798f56a8552776500d35fde843f9b57e8d164e94a8864736f6c63430008180033";

  
      type MockReceiptEncoderConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockReceiptEncoderConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockReceiptEncoder__factory extends ContractFactory {
    
      constructor(...args: MockReceiptEncoderConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockReceiptEncoder & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockReceiptEncoder__factory {
      return super.connect(runner) as MockReceiptEncoder__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockReceiptEncoderInterface {
      return new Interface(_abi) as MockReceiptEncoderInterface;
    }
    
    override attach(address: string | Addressable): MockReceiptEncoder {
      return super.attach(address) as MockReceiptEncoder;
    }
  static connect(address: string, runner?: ContractRunner | null): MockReceiptEncoder {
      return new Contract(address, _abi, runner) as unknown as MockReceiptEncoder;
    }
  }

  
  